### PR TITLE
Add translations into Russian

### PR DESCRIPTION
**Pull request by lexeii**
Translations have been tested in work for several days, but anyway, inaccuracies are possible. This topic has not yet entered the Russian language well enough; there is no established terminology. I, in most cases, focused on Wikipedia.

Some unresolved issues remain:

  - What is the best way to translate the unit of measurement `(c)` into Russian?
  - `glide / pitch mod`: is it `{glide / pitch} mod` or `{glide} / {pitch mod}`?
  - Same with the `sweep / filter mod`
  - What is `Inversion number`: is it the number of inversions or not?
  - What is `Ranks`? (It seems to me that this is something related to the organs.)

### CODE REVIEW

**Comment by davy7125** [comment]
A couple of days ago I got some help for a Japanese translation and now Russian... wonderful! This is a hard work, thank you very much for this.

Regarding the terminology:
* 1/100 of a pitch has been called **cents** in English. I'm not native English but probably it is related to cents like when we speak of coins (1 euro and 2 cents... for example). In the french translation I used "(c)" like "centième" which means "hundredth", I think this is more accurate. So if you think you can use the first letter of the Russian word for "hundredth" it can be nice. In some parts of the software I added the unit "1/100" so that we understand better.
* **glide / pitch mod** is used to characterize the timber of an instrument (if I remember well) and means: an instrument made of sounds with a pitch modulation, like a glide. So it is {glide} / {pitch mod}. In french I just used "pitch modulation"
* Same with: comprising a modulation filter like a sweep. I cannot explain more the word "sweep" unfortunately. In french I just used "filter modulation".
* the **inversion number** is the number of times a chord is inverted
https://en.wikipedia.org/wiki/Inversion_(music)
As a result, the fundamental is not at the same position.
* **Ranks** are indeed linked to the organ. Some organ stops are made of several ranks, it means that if you pull such a stop and you play ONE note, SEVERAL pipes will sound. This is typically the case in mixtures
https://en.wikipedia.org/wiki/Mixture_(organ_stop)

Do you want I add your name among the translators? This is in the "About Polyphone" => "Credits" section. If yes, you can also give me your email address (not mandatory).

**Comment by lexeii** [comment]
Thank you for the clarification.
I will fix the translations in a couple of hours (now I'm busy).

Yes, of course, I want my name to be added. My native name is Алексей, surname is Бобылёв. Transliterated is something like Aleksey Bobylev. Email is al.bobylev at gmail.com.

**Comment by lexeii** [comment]
Done: 57dcf21611392a897505ced6cee69e9d1b10b3b0

**Comment by davy7125** [comment]
Great! The sources have been updated
I just modified the names so that it's written with the Cyrillic alphabet (I copied what was used in the Serbian translation).

**Comment by lexeii** [comment]
Oh! Just remembered two more files:

  * polyphone.desktop: 7ad567405fb5dc7e986a158d9175257b7652d432
  * polyphone.xml: 08b4b7b3ce32d719f193237251383f1e1727b058

**Comment by davy7125** [comment]
Great! It's in the sources
Thank you very much

**Pull request merged**
