### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by lexeii**
A few changes that will make both the MD source code and the resulting HTML cleaner and more friendly.

### CODE REVIEW

**Comment by davy7125** [comment]
The PHP tool I'm using for parsing .md files doesn't support the definition of links (url and images) at the end of the files!
I'll merge this work manually, including:
* the small changes in the Russian version of "create a soundfont from scratch"
* the use of dd / dt
* wrappers <div class="doc_warning"> ... </div> and <div class="doc_notes"> ... </div> for the notes and warnings

**Comment by lexeii** [comment]
OK, thank you.

I used PHP Markdown Extra documentation for reference from here:
https://michelf.ca/projects/php-markdown/extra/

(Actually, this page is unavailable for me, so I used [Google cached page](https://webcache.googleusercontent.com/search?q=cache:6rRz-L4Ou7MJ:https://michelf.ca/projects/php-markdown/extra/+&cd=1&hl=ru&ct=clnk&gl=ua&client=firefox-b-d))

**Comment by davy7125** [comment]
Unfortunately I haven't been able to add the "info" or "warning" wrappers. I tried using comments but the library doesn't like them... And if I wrap in html code, we lose the MD formatting inside.

So what I did is: 
* the small changes in the Russian version of "create a soundfont from scratch"
* the use of dd / dt

I close the pull request and I hope the current state of the documentation is OK for you

**Comment by lexeii** [comment]
Thank you for your work.

I left two comments on your last commit.
Please make these small edits as well.

**Pull request closed without merging**
